### ISSUE TITLE
#1 - Easy navigation and access to desired information

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/legends-of-asgard#1]
I am a Mythology/Folklore enthusiast, I would like an area showing all the gods with links to their short blurbs and saga info displayed in eye catching card format, so that I may quickly find the sagas and all the information I need

## Acceptance Criteria

- [ ]  A one page structure containing several sections with information and images structured with HTML and Bootstrap and custom styled with CSS
- [ ]  The top section of the page must contain the title of the site and short description, navigation to important areas and a picture of each god that links to their section of information, possibly fixed to the bottom of the screen
- [ ]  Each section must be full width and height of the viewport and should snap when scrolled with images and information about the God and a Saga relating to them
- [ ]  Each god section should display the information in carousel form to allow for readability and information overflow
- [ ]  The site should be fully responsive on all major device widths

## Tasks

- [ ]  Create boilerplate HTML structure, with meta description and keywords and containing sections: header, main and footer
- [ ]  Link Bootstrap css and js cdn, fontawesome kit and custom css file
- [ ]  Create a nav inside the header and at least 7 sections within the main area with id’s of: #odin, #thor, #loki, #freya, #tyr #hel and #sif
- [ ]  Add navigation, title and description and standalone images of each God in a carousel like format, linking to their respective section with a background image of some epic scenery (carousel to be fixed to bottom of page)
- [ ]  Add carousel functionality to the header for each relating to the relevant God and add classes to make site full width and height
- [ ]  Add css scroll snapping and add bootstrap and media queries for responsiveness
