### ISSUE TITLE
#5 - Notification opt-in

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/legends-of-asgard#5]
I am a returning visitor of the site, and I would like to sign up for updates, so that I can find out when new gods and sagas are added

## Acceptance Criteria

- [ ]  A bell icon in the header section linking to a modal form to opt-in for updates
- [ ]  An option to opt-in for updates in the footer section

## Tasks

- [ ]  Add font-awesome css link into head of all pages
- [ ]  Add bell font-awesome icon into header which opens a modal containing an email field and submit button when clicked
